version: '3.9'

services:
  node-exporter:
    image: ${IMAGE_NAME:-prom/node-exporter}:${IMAGE_TAG:-latest}
    user: root
    entrypoint: ${CONFIG_PATH}/entrypoint.sh
    command:
      - --path.rootfs=${HOST_PATH}
      - --path.sysfs=${HOST_PATH}/sys
      - --path.procfs=${HOST_PATH}/proc
      - --collector.textfile.directory=${CONFIG_PATH}
      - --collector.filesystem.mount-points-exclude=^/(${MOUNT_POINTS_EXCLUDE})($$|/)
      - --no-collector.ipvs
    environment:
      CONFIG_PATH:
      NODE_ID: {{.Node.ID}}
      NODE_NAME: {{.Node.Hostname}}
    networks:
      metric-net:
    volumes:
      - /:${HOST_PATH}:ro,rslave
    configs:
      - source: entrypoint-config
        target: ${CONFIG_PATH}/entrypoint.sh
        mode: 0555
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

configs:
  entrypoint-config:
    name: ${ENTRYPOINT_CONFIG_NAME:-node-exporter-entrypoint}
    file: ./config/entrypoint.sh
